version: "3.8"

services:
  indic-seamless:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indic-seamless-service
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - PORT=8000
      - HOST=0.0.0.0
      - MODEL_NAME=ai4bharat/indic-seamless
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - huggingface_cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  huggingface_cache:
    driver: local

networks:
  default:
    name: indic-seamless-network
